### ISSUE TITLE
Detail Property disappears in release mode.

### ISSUE THREAD

**Issue by shuegelm** [khellang/Middleware#105] opened 2020-06-11 07:59 UTC
Hello me again.

Still using your great package. As the .NET Core example  I am also using this command inside the startup while being in debug mode:
`options.IncludeExceptionDetails = _ => _webHostEnvironment.IsDevelopment();`

The problem is: Being in release removes the `detail` property from the response body. In consequence the original error message disappears and just the error code and title are left. Maybe we could get rid of the `extension` property instead.
![image](https://user-images.githubusercontent.com/12783126/84360640-b19fba00-abca-11ea-8dd3-95e9c925a306.png)

Thanks in advance.

If you need further informations, I will add them.

Version: .NET Core SDK 3.1.300
Using: AddControllers and AddNewtonsoftJson as services.

**Comment by khellang** [comment] 2020-06-11 16:54
Hey! 👋 

Which version of the middleware are you using? I have a feeling this isn't v5? 🤔 

The extensions property shouldn't really be part of the final payload. It's a feature of System.Text.Json and Newtonsoft.Json that ASP.NET (and from v5, this middleware) uses to add dynamic data. The problem is that the MVC ProblemDetails type uses System.Text.Json's attribute, which Newtonsoft doesn't understand, so it's included. The built-in types have special converters that are added when calling AddNewtonsoftJson, but those won't work on sub-types. That's why I've also stopped using sub-types in v5.

**Comment by khellang** [comment] 2020-06-11 16:56
See #68 and #74 for more details 😊

**Comment by shuegelm** [comment] 2020-06-15 09:15
Thanks for your answer. I am not using the 5.0 version. Thats right. Is this version even backward compatible?

**Comment by khellang** [comment] 2020-06-15 09:32
> Is this version even backward compatible?

More or less. The target frameworks changed to `netcoreapp3.1` in order to use `JsonExtensionData` for adding exception details.

I don't think there are any necessary code changes, but there are some recommendations:

`ExceptionProblemDetails` has been deprecated (but it still exists), so if you previously have code like this:

```csharp
options.Map<NotImplementedException>(ex => new ExceptionProblemDetails(ex, StatusCodes.Status501NotImplemented));
```

You might want to change it to

```csharp
options.MapToStatusCode<NotImplementedException>(StatusCodes.Status501NotImplemented);
```

If you previously used `new StatusCodeProblemDetails(statusCode)`, you should now use `StatusCodeProblemDetails.Create(statusCode)`. This is to avoid creating sub-types of `ProblemDetails`, which doesn't play well with Newtonsoft.Json/System.Text.Json.

Other than that, I think you just have to upgrade and test. I haven't received any big complaints (except #102) yet and it's been downloaded ~30k times on NuGet 😅

**Comment by khellang** [comment] 2020-07-15 06:40
Hey @shuegelm! 👋 

Did you get to try 5.x? I'm pretty confident that it should fix your issue 😄

I don't think there's much for me to do on this issue, so I'll close it for now. Feel free to reopen if 5.x doesn't fix it for you 😅

**Closed by khellang** 2020-07-15 06:40 UTC

**Comment by luizen** [comment] 2023-10-23 17:24
Hi @khellang. 
I'm a bit confused as to whether this is actually working in the latest versions of the library.
What I am trying to achieve is to have the _detail_ property appear when running in production. However, in my case, I'm not using much exceptions. Instead I'm manually creating the ProblemDetails objects, using the ProblemDetailsFactory, and I am passing some custom text in the _detail_ parameter. For instance, when I want to return HTTP 422 in a business validation error situation, I'm doing something like this:
```
var pd = _problemDetailsFactory.CreateProblemDetails(
        httpContext,
        statusCode: statusCode,
        detail: "some extra details about the error",
        instance: httpContext.Request.Path);

return pd;
```

When running in production, the _detail_ property is missing. I don't think the _detail_ property is meant to be used only for exceptions...
So... could we simply make that property be always passed as is to the response? As far as I see, this is even how the .NET framework code itself behaves.

Thanks

**Comment by luizen** [comment] 2023-10-30 17:03
Hey @khellang, thanks for clarifying that :) I think I might have something else wrong going on here. I'll take a better look, but now knowing that it is supposed to work out of the box ;) Thanks!
